export { default as Header } from './sections/Header'
export { default as Footer } from './sections/Footer'
export { default as Sidebar } from './sections/Sidebar'
export { default as MainPage } from './MainPage'
export { default as Section1 } from './sections/Section1'
export { default as Section2 } from './sections/Section2'
export { default as Section3 } from './sections/Section3'
export { default as Section4 } from './sections/Section4'
export { default as NewsPage } from './sections/NewsPage'
export { default as SNSPage } from './sections/SNSPage'

export { default as SubPage } from './SubPage'